# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67cd9d7f0211bf30c7c456364b55e30533f7695d81696b3b2fb2c34e303c7c73ef7ad704ceae3444cc120fc956ab405418e5e0997ffea439668a796f7f097bfb

test:
  secret_key_base: 7d4111306df30df5f8ab2d59ff1ebbad838dac9fb8a3c41c8c01ebec30f3c5bbca18a3b34a311a909373c80d486fdcc9fad4153c7de1078c2b7a28e61131c33c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
